In [1]:
import requests  #get dta from website
from bs4 import BeautifulSoup
import pandas as pd
import json
import time

In [132]:
def scrape_movie(movie):

    url = movie["movie_url"]

    # Request movie page
    try:
        response = requests.get(
            url,
            headers={
                "User-Agent": "Mozilla/5.0",
                "Accept-Language": "en-US,en;q=0.9"
            },
            timeout=20
        )

    except requests.exceptions.RequestException as e:
        print("Connection error:", movie["title"])
        return None

    # Stop immediately if TMDB throttles us
    if response.status_code == 429:
        raise RuntimeError("TMDB_THROTTLED")

    if response.status_code != 200:
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    # JSON-LD data
    scripts = soup.find_all(
        "script",
        type="application/ld+json"
    )

    if not scripts:
        return None

    text = scripts[0].text.strip()
    text = text.replace("/* <![CDATA[ */", "")
    text = text.replace("/* ]]> */", "")

    data = json.loads(text)

    # Status, language, budget, revenue
    status = None
    language = None
    budget = None
    revenue = None

    for p in soup.find_all("p"):

        text = p.get_text(" ", strip=True)

        if text.startswith("Status"):
            status = text.replace("Status", "").strip()

        elif text.startswith("Original Language"):
            language = text.replace(
                "Original Language", ""
            ).strip()

        elif text.startswith("Budget"):
            budget = text.replace("Budget", "").strip()

        elif text.startswith("Revenue"):
            revenue = text.replace("Revenue", "").strip()

    # Keywords
    keywords = []

    keyword_section = soup.find(
        "section",
        class_="keywords"
    )

    if keyword_section:
        for a in keyword_section.find_all("a"):
            keywords.append(
                a.get_text(strip=True)
            )

    # Cast
    cast = []

    cast_section = soup.find(
        "section",
        class_="top_billed"
    )

    if cast_section:
        for card in cast_section.select("li.card"):

            actor = card.find("p")
            character = card.find(
                "p",
                class_="character"
            )

            if actor:
                cast.append({
                    "actor": actor.get_text(strip=True),
                    "character": character.get_text(
                        strip=True
                    ) if character else None
                })

    # Director and writers
    director = None
    writers = []

    for person in soup.select("li.profile"):

        name = person.find("a")
        role = person.find(
            "p",
            class_="character"
        )

        if not name or not role:
            continue

        name = name.get_text(strip=True)
        role = role.get_text(strip=True)

        if "Director" in role:
            director = name

        if "Writer" in role:
            writers.append(name)

    # Content Score
    content_score = None

    content_section = soup.find(
        "section",
        class_="content_score"
    )

    if content_section:
        score = content_section.select_one(
            ".content_score_wrapper > .content_score p"
        )

        if score:
            content_score = score.get_text(strip=True)

    # Final movie record
    movie_data = {
        "movie_id": movie["movie_id"],
        "title": data.get("name"),
        "movie_url": movie["movie_url"],
        "poster_url": movie["poster_url"],
        "release_date": movie["release_date"],
        "genres": data.get("genre", []),
        "overview": data.get("description"),
        "user_score": data.get(
            "aggregateRating", {}
        ).get("ratingValue"),
        "runtime": data.get("duration"),
        "director": director,
        "writers": writers,
        "cast": cast,
        "status": status,
        "original_language": language,
        "budget": budget,
        "revenue": revenue,
        "keywords": keywords,
        "content_score": content_score
    }

    return movie_data

In [31]:
def get_movie_list(page=1):

    url = f"https://www.themoviedb.org/movie?page={page}"

    response = requests.get(
        url,
        headers={
            "User-Agent": "Mozilla/5.0",
            "Accept-Language": "en-US,en;q=0.9"
        }
    )

    if response.status_code != 200:
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    movies = []

    for card in soup.select("div[data-object-id]"):

        link = card.find("a", href=lambda x: x and "/movie/" in x)

        if link:

            href = link["href"]
            title = card.find("h2")
            date = card.find("span", class_="release_date")
            poster = card.find("img")

            movies.append({
                "movie_id": href.split("/movie/")[1].split("-")[0],
                "title": title.get_text(strip=True) if title else None,
                "movie_url": "https://www.themoviedb.org" + href,
                "poster_url": poster.get("src") if poster else None,
                "release_date": date.get_text(strip=True) if date else None
            })

    return movies

In [137]:
def get_all_movies():

    all_movies = []
    page = 1

    while True:

        print("Scraping page:", page)

        page_movies = get_movie_list(page)

        if len(page_movies) == 0:
            print("No more movies found.")
            break

        all_movies.extend(page_movies)

        print("Movies collected:", len(all_movies))

        page += 1

    return all_movies

In [64]:
all_movies = get_all_movies()

print("Total movies collected:", len(all_movies))

Scraping page: 1
Movies collected: 20
Scraping page: 2
Movies collected: 40
Scraping page: 3
Movies collected: 60
Scraping page: 4
Movies collected: 80
Scraping page: 5
Movies collected: 100
Scraping page: 6
Movies collected: 120
Scraping page: 7
Movies collected: 140
Scraping page: 8
Movies collected: 160
Scraping page: 9
Movies collected: 180
Scraping page: 10
Movies collected: 200
Scraping page: 11
Movies collected: 220
Scraping page: 12
Movies collected: 240
Scraping page: 13
Movies collected: 260
Scraping page: 14
Movies collected: 280
Scraping page: 15
Movies collected: 300
Scraping page: 16
Movies collected: 320
Scraping page: 17
Movies collected: 340
Scraping page: 18
Movies collected: 360
Scraping page: 19
Movies collected: 380
Scraping page: 20
Movies collected: 400
Scraping page: 21
Movies collected: 420
Scraping page: 22
Movies collected: 440
Scraping page: 23
Movies collected: 460
Scraping page: 24
Movies collected: 480
Scraping page: 25
Movies collected: 500
Scraping page: 26
Movies collected: 520
Scraping page: 27
Movies collected: 540
Scraping page: 28
Movies collected: 560
Scraping page: 29
Movies collected: 580
Scraping page: 30
Movies collected: 600
Scraping page: 31
Movies collected: 620
Scraping page: 32
Movies collected: 640
Scraping page: 33
Movies collected: 660
Scraping page: 34
Movies collected: 680
Scraping page: 35
Movies collected: 700
Scraping page: 36
Movies collected: 720
Scraping page: 37
Movies collected: 740
Scraping page: 38
Movies collected: 760
Scraping page: 39
Movies collected: 780
Scraping page: 40
Movies collected: 800
Scraping page: 41
Movies collected: 820
Scraping page: 42
Movies collected: 840
Scraping page: 43
Movies collected: 860
Scraping page: 44
Movies collected: 880
Scraping page: 45
Movies collected: 900
Scraping page: 46
Movies collected: 920
Scraping page: 47
Movies collected: 940
Scraping page: 48
Movies collected: 960
Scraping page: 49
Movies collected: 980
Scraping page: 50
Movies collected: 1000
Scraping page: 51
Movies collected: 1020
Scraping page: 52
Movies collected: 1040
Scraping page: 53
Movies collected: 1060
Scraping page: 54
Movies collected: 1080
Scraping page: 55
Movies collected: 1100
Scraping page: 56
Movies collected: 1120
Scraping page: 57
Movies collected: 1140
Scraping page: 58
Movies collected: 1160
Scraping page: 59
Movies collected: 1180
Scraping page: 60
Movies collected: 1200
Scraping page: 61
Movies collected: 1220
Scraping page: 62
Movies collected: 1240
Scraping page: 63
Movies collected: 1260
Scraping page: 64
Movies collected: 1280
Scraping page: 65
Movies collected: 1300
Scraping page: 66
Movies collected: 1320
Scraping page: 67
Movies collected: 1340
Scraping page: 68
Movies collected: 1360
Scraping page: 69
Movies collected: 1380
Scraping page: 70
Movies collected: 1400
Scraping page: 71
Movies collected: 1420
Scraping page: 72
Movies collected: 1440
Scraping page: 73
Movies collected: 1460
Scraping page: 74
Movies collected: 1480
Scraping page: 75
Movies collected: 1500
Scraping page: 76
Movies collected: 1520
Scraping page: 77
Movies collected: 1540
Scraping page: 78
Movies collected: 1560
Scraping page: 79
Movies collected: 1580
Scraping page: 80
Movies collected: 1600
Scraping page: 81
Movies collected: 1620
Scraping page: 82
Movies collected: 1640
Scraping page: 83
Movies collected: 1660
Scraping page: 84
Movies collected: 1680
Scraping page: 85
Movies collected: 1700
Scraping page: 86
Movies collected: 1720
Scraping page: 87
Movies collected: 1740
Scraping page: 88
Movies collected: 1760
Scraping page: 89
Movies collected: 1780
Scraping page: 90
Movies collected: 1800
Scraping page: 91
Movies collected: 1820
Scraping page: 92
Movies collected: 1840
Scraping page: 93
Movies collected: 1860
Scraping page: 94
Movies collected: 1880
Scraping page: 95
Movies collected: 1900
Scraping page: 96
Movies collected: 1920
Scraping page: 97
Movies collected: 1940
Scraping page: 98
Movies collected: 1960
Scraping page: 99
Movies collected: 1980
Scraping page: 100
Movies collected: 2000
Scraping page: 101
Movies collected: 2020
Scraping page: 102
Movies collected: 2040
Scraping page: 103
Movies collected: 2060
Scraping page: 104
Movies collected: 2080
Scraping page: 105
Movies collected: 2100
Scraping page: 106
Movies collected: 2120
Scraping page: 107
Movies collected: 2140
Scraping page: 108
Movies collected: 2160
Scraping page: 109
Movies collected: 2180
Scraping page: 110
Movies collected: 2200
Scraping page: 111
Movies collected: 2220
Scraping page: 112
Movies collected: 2240
Scraping page: 113
Movies collected: 2260
Scraping page: 114
Movies collected: 2280
Scraping page: 115
Movies collected: 2300
Scraping page: 116
Movies collected: 2320
Scraping page: 117
Movies collected: 2340
Scraping page: 118
Movies collected: 2360
Scraping page: 119
Movies collected: 2380
Scraping page: 120
Movies collected: 2400
Scraping page: 121
Movies collected: 2420
Scraping page: 122
Movies collected: 2440
Scraping page: 123
Movies collected: 2460
Scraping page: 124
Movies collected: 2480
Scraping page: 125
Movies collected: 2500
Scraping page: 126
Movies collected: 2520
Scraping page: 127
Movies collected: 2540
Scraping page: 128
Movies collected: 2560
Scraping page: 129
Movies collected: 2580
Scraping page: 130
Movies collected: 2600
Scraping page: 131
Movies collected: 2620
Scraping page: 132
Movies collected: 2640
Scraping page: 133
Movies collected: 2660
Scraping page: 134
Movies collected: 2680
Scraping page: 135
Movies collected: 2700
Scraping page: 136
Movies collected: 2720
Scraping page: 137
Movies collected: 2740
Scraping page: 138
Movies collected: 2760
Scraping page: 139
Movies collected: 2780
Scraping page: 140
Movies collected: 2800
Scraping page: 141
Movies collected: 2820
Scraping page: 142
Movies collected: 2840
Scraping page: 143
Movies collected: 2860
Scraping page: 144
Movies collected: 2880
Scraping page: 145
Movies collected: 2900
Scraping page: 146
Movies collected: 2920
Scraping page: 147
Movies collected: 2940
Scraping page: 148
Movies collected: 2960
Scraping page: 149
Movies collected: 2980
Scraping page: 150
Movies collected: 3000
Scraping page: 151
Movies collected: 3020
Scraping page: 152
Movies collected: 3040
Scraping page: 153
Movies collected: 3060
Scraping page: 154
Movies collected: 3080
Scraping page: 155
Movies collected: 3100
Scraping page: 156
Movies collected: 3120
Scraping page: 157
Movies collected: 3140
Scraping page: 158
Movies collected: 3160
Scraping page: 159
Movies collected: 3180
Scraping page: 160
Movies collected: 3200
Scraping page: 161
Movies collected: 3220
Scraping page: 162
Movies collected: 3240
Scraping page: 163
Movies collected: 3260
Scraping page: 164
Movies collected: 3280
Scraping page: 165
Movies collected: 3300
Scraping page: 166
Movies collected: 3320
Scraping page: 167
Movies collected: 3340
Scraping page: 168
Movies collected: 3360
Scraping page: 169
Movies collected: 3380
Scraping page: 170
Movies collected: 3400
Scraping page: 171
Movies collected: 3420
Scraping page: 172
Movies collected: 3440
Scraping page: 173
Movies collected: 3460
Scraping page: 174
Movies collected: 3480
Scraping page: 175
Movies collected: 3500
Scraping page: 176
Movies collected: 3520
Scraping page: 177
Movies collected: 3540
Scraping page: 178
Movies collected: 3560
Scraping page: 179
Movies collected: 3580
Scraping page: 180
Movies collected: 3600
Scraping page: 181
Movies collected: 3620
Scraping page: 182
Movies collected: 3640
Scraping page: 183
Movies collected: 3660
Scraping page: 184
Movies collected: 3680
Scraping page: 185
Movies collected: 3700
Scraping page: 186
Movies collected: 3720
Scraping page: 187
Movies collected: 3740
Scraping page: 188
Movies collected: 3760
Scraping page: 189
Movies collected: 3780
Scraping page: 190
Movies collected: 3800
Scraping page: 191
Movies collected: 3820
Scraping page: 192
Movies collected: 3840
Scraping page: 193
Movies collected: 3860
Scraping page: 194
Movies collected: 3880
Scraping page: 195
Movies collected: 3900
Scraping page: 196
Movies collected: 3920
Scraping page: 197
Movies collected: 3940
Scraping page: 198
Movies collected: 3960
Scraping page: 199
Movies collected: 3980
Scraping page: 200
Movies collected: 4000
Scraping page: 201
Movies collected: 4020
Scraping page: 202
Movies collected: 4040
Scraping page: 203
Movies collected: 4060
Scraping page: 204
Movies collected: 4080
Scraping page: 205
Movies collected: 4100
Scraping page: 206
Movies collected: 4120
Scraping page: 207
Movies collected: 4140
Scraping page: 208
Movies collected: 4160
Scraping page: 209
Movies collected: 4180
Scraping page: 210
Movies collected: 4200
Scraping page: 211
Movies collected: 4220
Scraping page: 212
Movies collected: 4240
Scraping page: 213
Movies collected: 4260
Scraping page: 214
Movies collected: 4280
Scraping page: 215
Movies collected: 4300
Scraping page: 216
Movies collected: 4320
Scraping page: 217
Movies collected: 4340
Scraping page: 218
Movies collected: 4360
Scraping page: 219
Movies collected: 4380
Scraping page: 220
Movies collected: 4400
Scraping page: 221
Movies collected: 4420
Scraping page: 222
Movies collected: 4440
Scraping page: 223
Movies collected: 4460
Scraping page: 224
Movies collected: 4480
Scraping page: 225
Movies collected: 4500
Scraping page: 226
Movies collected: 4520
Scraping page: 227
Movies collected: 4540
Scraping page: 228
Movies collected: 4560
Scraping page: 229
Movies collected: 4580
Scraping page: 230
Movies collected: 4600
Scraping page: 231
Movies collected: 4620
Scraping page: 232
Movies collected: 4640
Scraping page: 233
Movies collected: 4660
Scraping page: 234
Movies collected: 4680
Scraping page: 235
Movies collected: 4700
Scraping page: 236
Movies collected: 4720
Scraping page: 237
Movies collected: 4740
Scraping page: 238
Movies collected: 4760
Scraping page: 239
Movies collected: 4780
Scraping page: 240
Movies collected: 4800
Scraping page: 241
Movies collected: 4820
Scraping page: 242
Movies collected: 4840
Scraping page: 243
Movies collected: 4860
Scraping page: 244
Movies collected: 4880
Scraping page: 245
Movies collected: 4900
Scraping page: 246
Movies collected: 4920
Scraping page: 247
Movies collected: 4940
Scraping page: 248
Movies collected: 4960
Scraping page: 249
Movies collected: 4980
Scraping page: 250
Movies collected: 5000
Scraping page: 251
Movies collected: 5020
Scraping page: 252
Movies collected: 5040
Scraping page: 253
Movies collected: 5060
Scraping page: 254
Movies collected: 5080
Scraping page: 255
Movies collected: 5100
Scraping page: 256
Movies collected: 5120
Scraping page: 257
Movies collected: 5140
Scraping page: 258
Movies collected: 5160
Scraping page: 259
Movies collected: 5180
Scraping page: 260
Movies collected: 5200
Scraping page: 261
Movies collected: 5220
Scraping page: 262
Movies collected: 5240
Scraping page: 263
Movies collected: 5260
Scraping page: 264
Movies collected: 5280
Scraping page: 265
Movies collected: 5300
Scraping page: 266
Movies collected: 5320
Scraping page: 267
Movies collected: 5340
Scraping page: 268
Movies collected: 5360
Scraping page: 269
Movies collected: 5380
Scraping page: 270
Movies collected: 5400
Scraping page: 271
Movies collected: 5420
Scraping page: 272
Movies collected: 5440
Scraping page: 273
Movies collected: 5460
Scraping page: 274
Movies collected: 5480
Scraping page: 275
Movies collected: 5500
Scraping page: 276
Movies collected: 5520
Scraping page: 277
Movies collected: 5540
Scraping page: 278
Movies collected: 5560
Scraping page: 279
Movies collected: 5580
Scraping page: 280
Movies collected: 5600
Scraping page: 281
Movies collected: 5620
Scraping page: 282
Movies collected: 5640
Scraping page: 283
Movies collected: 5660
Scraping page: 284
Movies collected: 5680
Scraping page: 285
Movies collected: 5700
Scraping page: 286
Movies collected: 5720
Scraping page: 287
Movies collected: 5740
Scraping page: 288
Movies collected: 5760
Scraping page: 289
Movies collected: 5780
Scraping page: 290
Movies collected: 5800
Scraping page: 291
Movies collected: 5820
Scraping page: 292
Movies collected: 5840
Scraping page: 293
Movies collected: 5860
Scraping page: 294
Movies collected: 5880
Scraping page: 295
Movies collected: 5900
Scraping page: 296
Movies collected: 5920
Scraping page: 297
Movies collected: 5940
Scraping page: 298
Movies collected: 5960
Scraping page: 299
Movies collected: 5980
Scraping page: 300
Movies collected: 6000
Scraping page: 301
Movies collected: 6020
Scraping page: 302
Movies collected: 6040
Scraping page: 303
Movies collected: 6060
Scraping page: 304
Movies collected: 6080
Scraping page: 305
Movies collected: 6100
Scraping page: 306
Movies collected: 6120
Scraping page: 307
Movies collected: 6140
Scraping page: 308
Movies collected: 6160
Scraping page: 309
Movies collected: 6180
Scraping page: 310
Movies collected: 6200
Scraping page: 311
Movies collected: 6220
Scraping page: 312
Movies collected: 6240
Scraping page: 313
Movies collected: 6260
Scraping page: 314
Movies collected: 6280
Scraping page: 315
Movies collected: 6300
Scraping page: 316
Movies collected: 6320
Scraping page: 317
Movies collected: 6340
Scraping page: 318
Movies collected: 6360
Scraping page: 319
Movies collected: 6380
Scraping page: 320
Movies collected: 6400
Scraping page: 321
Movies collected: 6420
Scraping page: 322
Movies collected: 6440
Scraping page: 323
Movies collected: 6460
Scraping page: 324
Movies collected: 6480
Scraping page: 325
Movies collected: 6500
Scraping page: 326
Movies collected: 6520
Scraping page: 327
Movies collected: 6540
Scraping page: 328
Movies collected: 6560
Scraping page: 329
Movies collected: 6580
Scraping page: 330
Movies collected: 6600
Scraping page: 331
Movies collected: 6620
Scraping page: 332
Movies collected: 6640
Scraping page: 333
Movies collected: 6660
Scraping page: 334
Movies collected: 6680
Scraping page: 335
Movies collected: 6700
Scraping page: 336
Movies collected: 6720
Scraping page: 337
Movies collected: 6740
Scraping page: 338
Movies collected: 6760
Scraping page: 339
Movies collected: 6780
Scraping page: 340
Movies collected: 6800
Scraping page: 341
Movies collected: 6820
Scraping page: 342
Movies collected: 6840
Scraping page: 343
Movies collected: 6860
Scraping page: 344
Movies collected: 6880
Scraping page: 345
Movies collected: 6900
Scraping page: 346
Movies collected: 6920
Scraping page: 347
Movies collected: 6940
Scraping page: 348
Movies collected: 6960
Scraping page: 349
Movies collected: 6980
Scraping page: 350
Movies collected: 7000
Scraping page: 351
Movies collected: 7020
Scraping page: 352
Movies collected: 7040
Scraping page: 353
Movies collected: 7060
Scraping page: 354
Movies collected: 7080
Scraping page: 355
Movies collected: 7100
Scraping page: 356
Movies collected: 7120
Scraping page: 357
Movies collected: 7140
Scraping page: 358
Movies collected: 7160
Scraping page: 359
Movies collected: 7180
Scraping page: 360
Movies collected: 7200
Scraping page: 361
Movies collected: 7220
Scraping page: 362
Movies collected: 7240
Scraping page: 363
Movies collected: 7260
Scraping page: 364
Movies collected: 7280
Scraping page: 365
Movies collected: 7300
Scraping page: 366
Movies collected: 7320
Scraping page: 367
Movies collected: 7340
Scraping page: 368
Movies collected: 7360
Scraping page: 369
Movies collected: 7380
Scraping page: 370
Movies collected: 7400
Scraping page: 371
Movies collected: 7420
Scraping page: 372
Movies collected: 7440
Scraping page: 373
Movies collected: 7460
Scraping page: 374
Movies collected: 7480
Scraping page: 375
Movies collected: 7500
Scraping page: 376
Movies collected: 7520
Scraping page: 377
Movies collected: 7540
Scraping page: 378
Movies collected: 7560
Scraping page: 379
Movies collected: 7580
Scraping page: 380
Movies collected: 7600
Scraping page: 381
Movies collected: 7620
Scraping page: 382
Movies collected: 7640
Scraping page: 383
Movies collected: 7660
Scraping page: 384
Movies collected: 7680
Scraping page: 385
Movies collected: 7700
Scraping page: 386
Movies collected: 7720
Scraping page: 387
Movies collected: 7740
Scraping page: 388
Movies collected: 7760
Scraping page: 389
Movies collected: 7780
Scraping page: 390
Movies collected: 7800
Scraping page: 391
Movies collected: 7820
Scraping page: 392
Movies collected: 7840
Scraping page: 393
Movies collected: 7860
Scraping page: 394
Movies collected: 7880
Scraping page: 395
Movies collected: 7900
Scraping page: 396
Movies collected: 7920
Scraping page: 397
Movies collected: 7940
Scraping page: 398
Movies collected: 7960
Scraping page: 399
Movies collected: 7980
Scraping page: 400
Movies collected: 8000
Scraping page: 401
Movies collected: 8020
Scraping page: 402
Movies collected: 8040
Scraping page: 403
Movies collected: 8060
Scraping page: 404
Movies collected: 8080
Scraping page: 405
Movies collected: 8100
Scraping page: 406
Movies collected: 8120
Scraping page: 407
Movies collected: 8140
Scraping page: 408
Movies collected: 8160
Scraping page: 409
Movies collected: 8180
Scraping page: 410
Movies collected: 8200
Scraping page: 411
Movies collected: 8220
Scraping page: 412
Movies collected: 8240
Scraping page: 413
Movies collected: 8260
Scraping page: 414
Movies collected: 8280
Scraping page: 415
Movies collected: 8300
Scraping page: 416
Movies collected: 8320
Scraping page: 417
Movies collected: 8340
Scraping page: 418
Movies collected: 8360
Scraping page: 419
Movies collected: 8380
Scraping page: 420
Movies collected: 8400
Scraping page: 421
Movies collected: 8420
Scraping page: 422
Movies collected: 8440
Scraping page: 423
Movies collected: 8460
Scraping page: 424
Movies collected: 8480
Scraping page: 425
Movies collected: 8500
Scraping page: 426
Movies collected: 8520
Scraping page: 427
Movies collected: 8540
Scraping page: 428
Movies collected: 8560
Scraping page: 429
Movies collected: 8580
Scraping page: 430
Movies collected: 8600
Scraping page: 431
Movies collected: 8620
Scraping page: 432
Movies collected: 8640
Scraping page: 433
Movies collected: 8660
Scraping page: 434
Movies collected: 8680
Scraping page: 435
Movies collected: 8700
Scraping page: 436
Movies collected: 8720
Scraping page: 437
Movies collected: 8740
Scraping page: 438
Movies collected: 8760
Scraping page: 439
Movies collected: 8780
Scraping page: 440
Movies collected: 8800
Scraping page: 441
Movies collected: 8820
Scraping page: 442
Movies collected: 8840
Scraping page: 443
Movies collected: 8860
Scraping page: 444
Movies collected: 8880
Scraping page: 445
Movies collected: 8900
Scraping page: 446
Movies collected: 8920
Scraping page: 447
Movies collected: 8940
Scraping page: 448
Movies collected: 8960
Scraping page: 449
Movies collected: 8980
Scraping page: 450
Movies collected: 9000
Scraping page: 451
Movies collected: 9020
Scraping page: 452
Movies collected: 9040
Scraping page: 453
Movies collected: 9060
Scraping page: 454
Movies collected: 9080
Scraping page: 455
Movies collected: 9100
Scraping page: 456
Movies collected: 9120
Scraping page: 457
Movies collected: 9140
Scraping page: 458
Movies collected: 9160
Scraping page: 459
Movies collected: 9180
Scraping page: 460
Movies collected: 9200
Scraping page: 461
Movies collected: 9220
Scraping page: 462
Movies collected: 9240
Scraping page: 463
Movies collected: 9260
Scraping page: 464
Movies collected: 9280
Scraping page: 465
Movies collected: 9300
Scraping page: 466
Movies collected: 9320
Scraping page: 467
Movies collected: 9340
Scraping page: 468
Movies collected: 9360
Scraping page: 469
Movies collected: 9380
Scraping page: 470
Movies collected: 9400
Scraping page: 471
Movies collected: 9420
Scraping page: 472
Movies collected: 9440
Scraping page: 473
Movies collected: 9460
Scraping page: 474
Movies collected: 9480
Scraping page: 475
Movies collected: 9500
Scraping page: 476
Movies collected: 9520
Scraping page: 477
Movies collected: 9540
Scraping page: 478
Movies collected: 9560
Scraping page: 479
Movies collected: 9580
Scraping page: 480
Movies collected: 9600

In [65]:
unique_movies = {}

for movie in all_movies:
    unique_movies[movie["movie_id"]] = movie

all_movies = list(unique_movies.values())

print("Before deduplication:", 10000)
print("After deduplication:", len(all_movies))

Before deduplication: 10000
After deduplication: 10000

In [122]:
def scrape_reviews(movie, max_reviews=3):

    url = movie["movie_url"] + "/reviews"

    try:
        response = requests.get(
            url,
            headers={
                "User-Agent": "Mozilla/5.0",
                "Accept-Language": "en-US,en;q=0.9"
            },
            timeout=20
        )

    except requests.exceptions.RequestException as e:
        print("Connection error:", movie["title"])
        return []

    if response.status_code != 200:
        print("Failed:", response.status_code, movie["title"])
        return []

    soup = BeautifulSoup(response.text, "html.parser")

    reviews = []

    for card in soup.select("div.card"):

        review_link = card.find(
            "a",
            href=lambda x: x and "/review/" in x
        )

        if not review_link:
            continue

        review_id = review_link["href"].split("/review/")[1].split("?")[0]

        author = None
        author_tag = card.select_one("h5 a")

        if author_tag:
            author = author_tag.get_text(strip=True)

        review_date = None
        date_tag = card.select_one("h5")

        if date_tag:
            date_text = date_tag.get_text(" ", strip=True)

            if " on " in date_text:
                review_date = date_text.split(" on ", 1)[1].strip()

        review_text = None
        teaser = card.select_one(".teaser")

        if teaser:
            review_text = teaser.get_text(" ", strip=True)

        reviews.append({
            "movie_id": movie["movie_id"],
            "review_id": review_id,
            "author": author,
            "review_date": review_date,
            "review_text": review_text
        })

        if len(reviews) >= max_reviews:
            break

    return reviews

In [124]:
len(reviews_data)

8900

In [130]:
all_movies_df = pd.DataFrame(all_movies)

all_movies_df.to_csv(
    "movie_list_10000.csv",
    index=False
)

print("Movies saved:", len(all_movies_df))

Movies saved: 10000

In [135]:
import time
import pandas as pd

movies_data_final = []
cast_data_final = []

for i, movie in enumerate(all_movies, start=1):

    try:
        result = scrape_movie(movie)

    except RuntimeError as e:

        if str(e) == "TMDB_THROTTLED":

            # Save everything collected so far
            pd.DataFrame(movies_data_final).to_csv(
                "movies_checkpoint.csv",
                index=False
            )

            pd.DataFrame(cast_data_final).to_csv(
                "movie_cast_checkpoint.csv",
                index=False
            )

            print()
            print("TMDB THROTTLED THE CONNECTION.")
            print("Scrape stopped at movie:", i)
            print("Movies collected:", len(movies_data_final))
            break

        raise

    if result is not None:

        cast = result.pop("cast", [])

        movies_data_final.append(result)

        for person in cast:

            cast_data_final.append({
                "movie_id": movie["movie_id"],
                "actor": person["actor"],
                "character": person["character"]
            })

    if i % 50 == 0:

        pd.DataFrame(movies_data_final).to_csv(
            "movies_checkpoint.csv",
            index=False
        )

        pd.DataFrame(cast_data_final).to_csv(
            "movie_cast_checkpoint.csv",
            index=False
        )

        print(
            "Movies processed:", i,
            "| Movies collected:", len(movies_data_final),
            "| Cast records:", len(cast_data_final)
        )

    time.sleep(2)

Connection error: The Mongoose
Connection error: Ice Cream Man
Connection error: Avengers: Infinity War
Movies processed: 50 | Movies collected: 47 | Cast records: 410
Movies processed: 100 | Movies collected: 97 | Cast records: 850
Movies processed: 150 | Movies collected: 147 | Cast records: 1291
Movies processed: 200 | Movies collected: 197 | Cast records: 1733
Movies processed: 250 | Movies collected: 247 | Cast records: 2181
Movies processed: 300 | Movies collected: 297 | Cast records: 2622
Movies processed: 350 | Movies collected: 347 | Cast records: 3065
Connection error: Gladiator II
Movies processed: 400 | Movies collected: 396 | Cast records: 3495
Movies processed: 450 | Movies collected: 446 | Cast records: 3934
Movies processed: 500 | Movies collected: 496 | Cast records: 4376
Movies processed: 550 | Movies collected: 546 | Cast records: 4824
Movies processed: 600 | Movies collected: 596 | Cast records: 5264
Movies processed: 650 | Movies collected: 646 | Cast records: 5710
Movies processed: 700 | Movies collected: 696 | Cast records: 6151
Movies processed: 750 | Movies collected: 746 | Cast records: 6601
Movies processed: 800 | Movies collected: 796 | Cast records: 7035
Movies processed: 850 | Movies collected: 846 | Cast records: 7477
Movies processed: 900 | Movies collected: 896 | Cast records: 7919
Movies processed: 950 | Movies collected: 946 | Cast records: 8369
Movies processed: 1000 | Movies collected: 996 | Cast records: 8819
Movies processed: 1050 | Movies collected: 1046 | Cast records: 9258
Movies processed: 1100 | Movies collected: 1096 | Cast records: 9704
Movies processed: 1150 | Movies collected: 1146 | Cast records: 10150
Movies processed: 1200 | Movies collected: 1196 | Cast records: 10596
Movies processed: 1250 | Movies collected: 1246 | Cast records: 11044
Movies processed: 1300 | Movies collected: 1296 | Cast records: 11494
Movies processed: 1350 | Movies collected: 1346 | Cast records: 11936
Movies processed: 1400 | Movies collected: 1396 | Cast records: 12379
Connection error: The Hills Have Eyes
Movies processed: 1450 | Movies collected: 1445 | Cast records: 12810
Movies processed: 1500 | Movies collected: 1495 | Cast records: 13260
Movies processed: 1550 | Movies collected: 1545 | Cast records: 13709
Movies processed: 1600 | Movies collected: 1595 | Cast records: 14158
Movies processed: 1650 | Movies collected: 1645 | Cast records: 14594
Movies processed: 1700 | Movies collected: 1695 | Cast records: 15036
Movies processed: 1750 | Movies collected: 1745 | Cast records: 15473
Movies processed: 1800 | Movies collected: 1795 | Cast records: 15911
Movies processed: 1850 | Movies collected: 1845 | Cast records: 16359
Movies processed: 1900 | Movies collected: 1895 | Cast records: 16808
Movies processed: 1950 | Movies collected: 1945 | Cast records: 17252
Movies processed: 2000 | Movies collected: 1995 | Cast records: 17702
Movies processed: 2050 | Movies collected: 2045 | Cast records: 18145
Movies processed: 2100 | Movies collected: 2095 | Cast records: 18591
Movies processed: 2150 | Movies collected: 2145 | Cast records: 19027
Movies processed: 2200 | Movies collected: 2195 | Cast records: 19472
Movies processed: 2250 | Movies collected: 2245 | Cast records: 19918
Movies processed: 2300 | Movies collected: 2295 | Cast records: 20361
Movies processed: 2350 | Movies collected: 2345 | Cast records: 20803
Movies processed: 2400 | Movies collected: 2395 | Cast records: 21246
Movies processed: 2450 | Movies collected: 2445 | Cast records: 21690
Movies processed: 2500 | Movies collected: 2495 | Cast records: 22137
Movies processed: 2550 | Movies collected: 2545 | Cast records: 22586
Movies processed: 2600 | Movies collected: 2595 | Cast records: 23036
Movies processed: 2650 | Movies collected: 2645 | Cast records: 23472
Movies processed: 2700 | Movies collected: 2695 | Cast records: 23911
Movies processed: 2750 | Movies collected: 2745 | Cast records: 24360
Movies processed: 2800 | Movies collected: 2795 | Cast records: 24806
Movies processed: 2850 | Movies collected: 2845 | Cast records: 25238
Movies processed: 2900 | Movies collected: 2895 | Cast records: 25684
Movies processed: 2950 | Movies collected: 2945 | Cast records: 26131
Movies processed: 3000 | Movies collected: 2995 | Cast records: 26571
Movies processed: 3050 | Movies collected: 3045 | Cast records: 27004
Movies processed: 3100 | Movies collected: 3095 | Cast records: 27454
Movies processed: 3150 | Movies collected: 3145 | Cast records: 27902
Movies processed: 3200 | Movies collected: 3195 | Cast records: 28344
Movies processed: 3250 | Movies collected: 3245 | Cast records: 28783
Movies processed: 3300 | Movies collected: 3295 | Cast records: 29232
Movies processed: 3350 | Movies collected: 3345 | Cast records: 29673
Movies processed: 3400 | Movies collected: 3395 | Cast records: 30109
Movies processed: 3450 | Movies collected: 3445 | Cast records: 30544
Movies processed: 3500 | Movies collected: 3495 | Cast records: 30984
Movies processed: 3550 | Movies collected: 3545 | Cast records: 31426
Movies processed: 3600 | Movies collected: 3595 | Cast records: 31872
Movies processed: 3650 | Movies collected: 3645 | Cast records: 32312
Movies processed: 3700 | Movies collected: 3695 | Cast records: 32746
Movies processed: 3750 | Movies collected: 3745 | Cast records: 33196
Movies processed: 3800 | Movies collected: 3795 | Cast records: 33634
Movies processed: 3850 | Movies collected: 3845 | Cast records: 34074
Movies processed: 3900 | Movies collected: 3895 | Cast records: 34509
Movies processed: 3950 | Movies collected: 3945 | Cast records: 34950
Movies processed: 4000 | Movies collected: 3995 | Cast records: 35390
Movies processed: 4050 | Movies collected: 4045 | Cast records: 35831
Movies processed: 4100 | Movies collected: 4095 | Cast records: 36270
Movies processed: 4150 | Movies collected: 4145 | Cast records: 36712
Movies processed: 4200 | Movies collected: 4195 | Cast records: 37152
Movies processed: 4250 | Movies collected: 4245 | Cast records: 37582
Movies processed: 4300 | Movies collected: 4295 | Cast records: 38020
Movies processed: 4350 | Movies collected: 4345 | Cast records: 38456
Movies processed: 4400 | Movies collected: 4395 | Cast records: 38889
Movies processed: 4450 | Movies collected: 4445 | Cast records: 39330
Movies processed: 4500 | Movies collected: 4495 | Cast records: 39771
Movies processed: 4550 | Movies collected: 4545 | Cast records: 40214
Movies processed: 4600 | Movies collected: 4595 | Cast records: 40657
Movies processed: 4650 | Movies collected: 4645 | Cast records: 41095
Movies processed: 4700 | Movies collected: 4695 | Cast records: 41537
Movies processed: 4750 | Movies collected: 4745 | Cast records: 41976
Movies processed: 4800 | Movies collected: 4795 | Cast records: 42422
Movies processed: 4850 | Movies collected: 4845 | Cast records: 42872
Movies processed: 4900 | Movies collected: 4895 | Cast records: 43317
Connection error: Wayne's World
Connection error: My Stepmother Is an Alien
Movies processed: 4950 | Movies collected: 4943 | Cast records: 43739
Movies processed: 5000 | Movies collected: 4993 | Cast records: 44179
Movies processed: 5050 | Movies collected: 5043 | Cast records: 44620
Movies processed: 5100 | Movies collected: 5093 | Cast records: 45062
Movies processed: 5150 | Movies collected: 5143 | Cast records: 45512
Movies processed: 5200 | Movies collected: 5193 | Cast records: 45947
Movies processed: 5250 | Movies collected: 5243 | Cast records: 46393
Movies processed: 5300 | Movies collected: 5293 | Cast records: 46833
Movies processed: 5350 | Movies collected: 5343 | Cast records: 47278
Movies processed: 5400 | Movies collected: 5393 | Cast records: 47721
Movies processed: 5450 | Movies collected: 5443 | Cast records: 48164
Movies processed: 5500 | Movies collected: 5493 | Cast records: 48601
Movies processed: 5550 | Movies collected: 5543 | Cast records: 49034
Movies processed: 5600 | Movies collected: 5593 | Cast records: 49474
Movies processed: 5650 | Movies collected: 5643 | Cast records: 49923
Movies processed: 5700 | Movies collected: 5693 | Cast records: 50373
Movies processed: 5750 | Movies collected: 5743 | Cast records: 50798
Movies processed: 5800 | Movies collected: 5793 | Cast records: 51233
Movies processed: 5850 | Movies collected: 5843 | Cast records: 51677
Movies processed: 5900 | Movies collected: 5893 | Cast records: 52113
Movies processed: 5950 | Movies collected: 5943 | Cast records: 52537
Movies processed: 6000 | Movies collected: 5993 | Cast records: 52975
Movies processed: 6050 | Movies collected: 6043 | Cast records: 53387
Movies processed: 6100 | Movies collected: 6093 | Cast records: 53818
Movies processed: 6150 | Movies collected: 6143 | Cast records: 54257
Movies processed: 6200 | Movies collected: 6193 | Cast records: 54678
Movies processed: 6250 | Movies collected: 6243 | Cast records: 55124
Movies processed: 6300 | Movies collected: 6293 | Cast records: 55541
Movies processed: 6350 | Movies collected: 6343 | Cast records: 55988
Movies processed: 6400 | Movies collected: 6393 | Cast records: 56414
Movies processed: 6450 | Movies collected: 6443 | Cast records: 56842
Movies processed: 6500 | Movies collected: 6493 | Cast records: 57283
Movies processed: 6550 | Movies collected: 6543 | Cast records: 57721
Movies processed: 6600 | Movies collected: 6593 | Cast records: 58151
Movies processed: 6650 | Movies collected: 6643 | Cast records: 58587
Movies processed: 6700 | Movies collected: 6693 | Cast records: 59037
Movies processed: 6750 | Movies collected: 6743 | Cast records: 59486

TMDB THROTTLED THE CONNECTION.
Scrape stopped at movie: 6772
Movies collected: 6764

In [136]:
movies = pd.DataFrame(movies_data_final)
movie_cast = pd.DataFrame(cast_data_final)

# Save detailed movie data
movies.to_csv(
    "movies.csv",
    index=False
)

# Save cast data
movie_cast.to_csv(
    "movie_cast.csv",
    index=False
)

print("Movies saved:", len(movies))
print("Cast records saved:", len(movie_cast))

Movies saved: 6764
Cast records saved: 59675

In [138]:
movies = pd.DataFrame(movies_data_final)
movie_cast = pd.DataFrame(cast_data_final)

movies.to_csv("movies.csv", index=False)
movie_cast.to_csv("movie_cast.csv", index=False)

In [2]:
import pandas as pd
import numpy as np
import ast
import re

In [3]:
movies = pd.read_csv("movies.csv")
movie_cast = pd.read_csv("movie_cast.csv")
movie_reviews = pd.read_csv("movie_reviews.csv")

In [4]:
movie_cast = pd.read_csv("movie_cast_checkpoint.csv")

In [5]:
movies.head()

,movie_id,title,movie_url,poster_url,release_date,genres,overview,user_score,runtime,director,writers,status,original_language,budget,revenue,keywords,content_score
0,969681,Spider-Man: Brand New Day,https://www.themoviedb.org/movie/969681-spider...,https://media.themoviedb.org/t/p/w220_and_h330...,"July 30, 2026","['Science Fiction', 'Action', 'Adventure']",Fighting crime full-time as Spider-Man in a wo...,7.860,PT2H25M,Destin Daniel Cretton,"['Erik Sommers', 'Chris McKenna']",Released,English,"$225,000,000","$2,478,502,286","['new york city', 'secret identity', 'hero', '...",100
1,1423191,Resident Evil,https://www.themoviedb.org/movie/1423191-resid...,https://media.themoviedb.org/t/p/w220_and_h330...,"September 17, 2026","['Horror', 'Science Fiction', 'Adventure']",Medical courier Bryan unwittingly finds himsel...,7.299,PT1H35M,Zach Cregger,"['Zach Cregger', 'Shay Hatten']",Released,English,"$75,000,000","$123,281,812","['outbreak', 'survival', 'zombie', 'based on v...",100
2,1101383,The End of Oak Street,https://www.themoviedb.org/movie/1101383-the-e...,https://media.themoviedb.org/t/p/w220_and_h330...,"August 14, 2026","['Science Fiction', 'Mystery', 'Thriller']",After a mysterious cosmic event rips Oak Stree...,7.003,PT1H40M,David Robert Mitchell,['David Robert Mitchell'],Released,English,"$80,000,000","$120,363,694","['teleportation', 'giant snake', 'family relat...",100
3,1204680,Coyote vs. Acme,https://www.themoviedb.org/movie/1204680-coyot...,https://media.themoviedb.org/t/p/w220_and_h330...,"August 20, 2026","['Comedy', 'Adventure', 'Family']",After Acme products fail him one too many time...,7.556,PT1H43M,Dave Green,[],Released,English,"$72,000,000","$79,825,108","['judge', 'lawsuit', 'lawyer', 'courtroom', 'u...",100
4,1368337,The Odyssey,https://www.themoviedb.org/movie/1368337-the-o...,https://media.themoviedb.org/t/p/w220_and_h330...,"July 17, 2026","['Adventure', 'Action', 'Fantasy']","Odysseus, the legendary King of Ithaca, embark...",8.000,PT2H53M,Christopher Nolan,['Christopher Nolan'],Released,English,"$250,000,000","$1,723,918,419","['greek mythology', 'trojan war', 'ship', 'his...",100

In [6]:
movies_clean = movies.copy()
movie_cast_clean = movie_cast.copy()
movie_reviews_clean = movie_reviews.copy()

In [7]:
movies.shape

(6764, 17)

In [8]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 6764 entries, 0 to 6763
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           6764 non-null   int64
 1   title              6764 non-null   str
 2   movie_url          6764 non-null   str
 3   poster_url         6758 non-null   str
 4   release_date       6764 non-null   str
 5   genres             6764 non-null   str
 6   overview           6743 non-null   str
 7   user_score         6639 non-null   float64
 8   runtime            6701 non-null   str
 9   director           6749 non-null   str
 10  writers            6764 non-null   str
 11  status             6764 non-null   str
 12  original_language  6764 non-null   str
 13  budget             6764 non-null   str
 14  revenue            6764 non-null   str
 15  keywords           6764 non-null   str
 16  content_score      6764 non-null   int64
dtypes: float64(1), int64(2), str(14)
memory usage: 5.5 MB

In [9]:
movies.isna().sum()

movie_id               0
title                  0
movie_url              0
poster_url             6
release_date           0
genres                 0
overview              21
user_score           125
runtime               63
director              15
writers                0
status                 0
original_language      0
budget                 0
revenue                0
keywords               0
content_score          0
dtype: int64

In [10]:
(movies == "").sum()

movie_id             0
title                0
movie_url            0
poster_url           0
release_date         0
genres               0
overview             0
user_score           0
runtime              0
director             0
writers              0
status               0
original_language    0
budget               0
revenue              0
keywords             0
content_score        0
dtype: int64

In [14]:
movies_clean["release_date"] = pd.to_datetime(
    movies_clean["release_date"],
    errors="coerce"
)

movies_clean["release_year"] = movies_clean["release_date"].dt.year

In [15]:
movies_clean[["release_date", "release_year"]].head()

  release_date  release_year
0   2026-07-30          2026
1   2026-09-17          2026
2   2026-08-14          2026
3   2026-08-20          2026
4   2026-07-17          2026

In [16]:
movies_clean[
    ["user_score", "content_score", "runtime", "budget", "revenue"]
].head(10)

   user_score  content_score  runtime        budget         revenue
0       7.860            100  PT2H25M  $225,000,000  $2,478,502,286
1       7.299            100  PT1H35M   $75,000,000    $123,281,812
2       7.003            100  PT1H40M   $80,000,000    $120,363,694
3       7.556            100  PT1H43M   $72,000,000     $79,825,108
4       8.000            100  PT2H53M  $250,000,000  $1,723,918,419
5       8.073            100   PT2H3M             -               -
6       6.723            100  PT1H36M   $40,000,000     $20,824,283
7       8.330            100  PT1H50M             -               -
8       7.600            100  PT1H35M             -               -
9       7.393            100  PT1H55M  $250,000,000    $308,159,595

In [17]:
movies_clean[
    ["user_score", "content_score", "runtime", "budget", "revenue"]
].dtypes

user_score       float64
content_score      int64
runtime              str
budget               str
revenue              str
dtype: object

In [18]:
def runtime_to_minutes(runtime):
    if pd.isna(runtime):
        return np.nan

    hours = 0
    minutes = 0

    hour_match = re.search(r"(\d+)H", runtime)
    minute_match = re.search(r"(\d+)M", runtime)

    if hour_match:
        hours = int(hour_match.group(1))

    if minute_match:
        minutes = int(minute_match.group(1))

    return hours * 60 + minutes


movies_clean["runtime_minutes"] = movies_clean["runtime"].apply(
    runtime_to_minutes
)

In [19]:
movies_clean[["runtime", "runtime_minutes"]].head(10)

   runtime  runtime_minutes
0  PT2H25M            145.0
1  PT1H35M             95.0
2  PT1H40M            100.0
3  PT1H43M            103.0
4  PT2H53M            173.0
5   PT2H3M            123.0
6  PT1H36M             96.0
7  PT1H50M            110.0
8  PT1H35M             95.0
9  PT1H55M            115.0

In [20]:
movies_clean

,movie_id,title,movie_url,poster_url,release_date,genres,overview,user_score,runtime,director,writers,status,original_language,budget,revenue,keywords,content_score,release_year,runtime_minutes
0,969681,Spider-Man: Brand New Day,https://www.themoviedb.org/movie/969681-spider...,https://media.themoviedb.org/t/p/w220_and_h330...,2026-07-30,"['Science Fiction', 'Action', 'Adventure']",Fighting crime full-time as Spider-Man in a wo...,7.860,PT2H25M,Destin Daniel Cretton,"['Erik Sommers', 'Chris McKenna']",Released,English,"$225,000,000","$2,478,502,286","['new york city', 'secret identity', 'hero', '...",100,2026,145.0
1,1423191,Resident Evil,https://www.themoviedb.org/movie/1423191-resid...,https://media.themoviedb.org/t/p/w220_and_h330...,2026-09-17,"['Horror', 'Science Fiction', 'Adventure']",Medical courier Bryan unwittingly finds himsel...,7.299,PT1H35M,Zach Cregger,"['Zach Cregger', 'Shay Hatten']",Released,English,"$75,000,000","$123,281,812","['outbreak', 'survival', 'zombie', 'based on v...",100,2026,95.0
2,1101383,The End of Oak Street,https://www.themoviedb.org/movie/1101383-the-e...,https://media.themoviedb.org/t/p/w220_and_h330...,2026-08-14,"['Science Fiction', 'Mystery', 'Thriller']",After a mysterious cosmic event rips Oak Stree...,7.003,PT1H40M,David Robert Mitchell,['David Robert Mitchell'],Released,English,"$80,000,000","$120,363,694","['teleportation', 'giant snake', 'family relat...",100,2026,100.0
3,1204680,Coyote vs. Acme,https://www.themoviedb.org/movie/1204680-coyot...,https://media.themoviedb.org/t/p/w220_and_h330...,2026-08-20,"['Comedy', 'Adventure', 'Family']",After Acme products fail him one too many time...,7.556,PT1H43M,Dave Green,[],Released,English,"$72,000,000","$79,825,108","['judge', 'lawsuit', 'lawyer', 'courtroom', 'u...",100,2026,103.0
4,1368337,The Odyssey,https://www.themoviedb.org/movie/1368337-the-o...,https://media.themoviedb.org/t/p/w220_and_h330...,2026-07-17,"['Adventure', 'Action', 'Fantasy']","Odysseus, the legendary King of Ithaca, embark...",8.000,PT2H53M,Christopher Nolan,['Christopher Nolan'],Released,English,"$250,000,000","$1,723,918,419","['greek mythology', 'trojan war', 'ship', 'his...",100,2026,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6759,38363,Fair Game,https://www.themoviedb.org/movie/38363-fair-game,https://media.themoviedb.org/t/p/w220_and_h330...,2010-05-20,"['Drama', 'Thriller']",A devoted wife and mother leads a secret life ...,6.452,PT1H48M,Doug Liman,[],Released,English,"$22,000,000","$25,806,953","['central intelligence agency (cia)', 'nuclear...",100,2010,108.0
6760,16873,Battle for Terra,https://www.themoviedb.org/movie/16873-battle-...,https://media.themoviedb.org/t/p/w220_and_h330...,2007-09-06,"['Action', 'Adventure', 'Animation', 'Science ...","A peaceful alien planet faces annihilation, as...",6.129,PT1H25M,Aristomenis Tsirbas,[],Released,English,"$4,000,000","$6,101,046","['mutiny', 'cave', 'chase', 'invasion', 'surre...",100,2007,85.0
6761,11860,Sabrina,https://www.themoviedb.org/movie/11860-sabrina,https://media.themoviedb.org/t/p/w220_and_h330...,1995-12-15,"['Romance', 'Drama', 'Comedy']","After her return from school in Paris, a playb...",6.206,PT2H7M,Sydney Pollack,[],Released,English,"$58,000,000","$53,672,080","['paris, france', 'sibling relationship', 'cha...",100,1995,127.0
6762,9642,Asterix and the Vikings,https://www.themoviedb.org/movie/9642-asterix-...,https://media.themoviedb.org/t/p/w220_and_h330...,2006-04-12,"['Family', 'Animation', 'Comedy', 'Adventure']",Asterix and Obelix have been given a tough mis...,6.105,PT1H18M,Jesper Møller,[],Released,French,-,"$22,501,596","['france', 'magic', 'village', 'vikings (norse...",100,2006,78.0
6763,549514,Fatale,https://www.themoviedb.org/movie/549514-fatale,https://media.themoviedb.org/t/p/w220_and_h330...,2020-12-18,"['Drama', 'Thriller']","After a wild one-night stand, successful sport...",6.040,PT1H42M,Deon Taylor,['David Loughery'],Released,English,-,-,"['california', 'husband wife relationship', 'm...",100,2020,102.0

In [21]:
movies_clean["budget"] = (
    movies_clean["budget"]
    .replace("-", np.nan)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

movies_clean["revenue"] = (
    movies_clean["revenue"]
    .replace("-", np.nan)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [22]:
movies_clean[["budget", "revenue"]].head(10)

        budget       revenue
0  225000000.0  2.478502e+09
1   75000000.0  1.232818e+08
2   80000000.0  1.203637e+08
3   72000000.0  7.982511e+07
4  250000000.0  1.723918e+09
5          NaN           NaN
6   40000000.0  2.082428e+07
7          NaN           NaN
8          NaN           NaN
9  250000000.0  3.081596e+08

In [23]:
movies_clean[["genres", "writers", "keywords"]].head(10)

,genres,writers,keywords
0,"['Science Fiction', 'Action', 'Adventure']","['Erik Sommers', 'Chris McKenna']","['new york city', 'secret identity', 'hero', '..."
1,"['Horror', 'Science Fiction', 'Adventure']","['Zach Cregger', 'Shay Hatten']","['outbreak', 'survival', 'zombie', 'based on v..."
2,"['Science Fiction', 'Mystery', 'Thriller']",['David Robert Mitchell'],"['teleportation', 'giant snake', 'family relat..."
3,"['Comedy', 'Adventure', 'Family']",[],"['judge', 'lawsuit', 'lawyer', 'courtroom', 'u..."
4,"['Adventure', 'Action', 'Fantasy']",['Christopher Nolan'],"['greek mythology', 'trojan war', 'ship', 'his..."
5,"['Action', 'Horror', 'Science Fiction']","['Yeon Sang-ho', 'Choi Gyu-seok']","['zombie', 'vaccine', 'ambivalent']"
6,"['Action', 'Thriller']","['J.P. Davis', 'Lindsay Michel']","['revenge', 'conspiracy', 'one man army', 'car..."
7,"['Romance', 'Comedy']",[],"['based on novel or book', 'professor', 'love'..."
8,"['Action', 'Thriller']",['Tom Boyle'],[]
9,"['Family', 'Fantasy', 'Comedy', 'Adventure']",[],"['ocean', 'sailboat', 'sea', ""leaving one's fa..."

In [24]:
movies_clean[["genres", "writers", "keywords"]].dtypes

genres      str
writers     str
keywords    str
dtype: object

In [25]:
import ast

list_columns = ["genres", "writers", "keywords"]

for col in list_columns:
    movies_clean[col] = movies_clean[col].apply(
        lambda x: ast.literal_eval(x) if pd.notna(x) else []
    )

In [26]:
movies_clean[["genres", "writers", "keywords"]].head()

,genres,writers,keywords
0,"[Science Fiction, Action, Adventure]","[Erik Sommers, Chris McKenna]","[new york city, secret identity, hero, mutatio..."
1,"[Horror, Science Fiction, Adventure]","[Zach Cregger, Shay Hatten]","[outbreak, survival, zombie, based on video ga..."
2,"[Science Fiction, Mystery, Thriller]",[David Robert Mitchell],"[teleportation, giant snake, family relationsh..."
3,"[Comedy, Adventure, Family]",[],"[judge, lawsuit, lawyer, courtroom, unlikely f..."
4,"[Adventure, Action, Fantasy]",[Christopher Nolan],"[greek mythology, trojan war, ship, historical..."

In [27]:
movie_genres = movies_clean[["movie_id", "genres"]].explode("genres")

movie_genres = movie_genres.rename(
    columns={"genres": "genre"}
)

movie_genres = movie_genres[
    movie_genres["genre"].notna() &
    (movie_genres["genre"] != "")
]

movie_genres.head()

   movie_id            genre
0    969681  Science Fiction
0    969681           Action
0    969681        Adventure
1   1423191           Horror
1   1423191  Science Fiction

In [28]:
movie_genres = movie_genres.reset_index(drop=True)

In [29]:
movie_writers = movies_clean[["movie_id", "writers"]].explode("writers")

movie_writers = movie_writers.rename(
    columns={"writers": "writer"}
)

movie_writers = movie_writers[
    movie_writers["writer"].notna() &
    (movie_writers["writer"] != "")
]

movie_writers = movie_writers.drop_duplicates().reset_index(drop=True)

movie_writers.head()

   movie_id                 writer
0    969681           Erik Sommers
1    969681          Chris McKenna
2   1423191           Zach Cregger
3   1423191            Shay Hatten
4   1101383  David Robert Mitchell

In [30]:
movie_keywords = movies_clean[["movie_id", "keywords"]].explode("keywords")

movie_keywords = movie_keywords.rename(
    columns={"keywords": "keyword"}
)

movie_keywords = movie_keywords[
    movie_keywords["keyword"].notna() &
    (movie_keywords["keyword"] != "")
]

movie_keywords = movie_keywords.drop_duplicates().reset_index(drop=True)

movie_keywords.head()

   movie_id          keyword
0    969681    new york city
1    969681  secret identity
2    969681             hero
3    969681         mutation
4    969681          villain

In [31]:
movie_cast_clean = movie_cast.copy()
movie_reviews_clean = movie_reviews.copy()

# Clean cast data
for col in ["actor", "character"]:
    movie_cast_clean[col] = (
        movie_cast_clean[col]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

# Clean review data
for col in ["author", "review_text"]:
    movie_reviews_clean[col] = (
        movie_reviews_clean[col]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

# Convert review dates
movie_reviews_clean["review_date"] = pd.to_datetime(
    movie_reviews_clean["review_date"],
    errors="coerce"
)

# Remove exact duplicate cast records
movie_cast_clean = movie_cast_clean.drop_duplicates().reset_index(drop=True)

# Each review ID should identify one review
movie_reviews_clean = movie_reviews_clean.drop_duplicates(
    subset="review_id"
).reset_index(drop=True)

In [32]:
print("Cast:", movie_cast_clean.shape)
print("Reviews:", movie_reviews_clean.shape)

movie_cast_clean.info()
movie_reviews_clean.info()

Cast: (59674, 3)
Reviews: (8900, 5)
<class 'pandas.DataFrame'>
RangeIndex: 59674 entries, 0 to 59673
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   movie_id   59674 non-null  int64
 1   actor      59674 non-null  string
 2   character  58935 non-null  string
dtypes: int64(1), string(2)
memory usage: 2.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 8900 entries, 0 to 8899
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     8900 non-null   int64
 1   review_id    8900 non-null   str
 2   author       8900 non-null   string
 3   review_date  8900 non-null   datetime64[us]
 4   review_text  8899 non-null   string
dtypes: datetime64[us](1), int64(1), str(1), string(2)
memory usage: 5.0 MB

In [33]:
print("Total reviews:", len(movie_reviews))

print(
    "Movies with reviews:",
    movie_reviews["movie_id"].nunique()
)

print(
    "Total movies in our dataset:",
    movies["movie_id"].nunique()
)

coverage = (
    movie_reviews["movie_id"].nunique()
    / movies["movie_id"].nunique()
) * 100

print(f"Movie review coverage: {coverage:.2f}%")

Total reviews: 8900
Movies with reviews: 3839
Total movies in our dataset: 6764
Movie review coverage: 56.76%

In [35]:
movies_table = movies_clean.drop(
    columns=["genres", "writers", "keywords", "runtime"]
).copy()

movies_table = movies_table.drop_duplicates(
    subset="movie_id"
).reset_index(drop=True)

In [36]:
print("Duplicate movie IDs:", movies_table["movie_id"].duplicated().sum())

movie_ids = set(movies_table["movie_id"])

supporting_tables = {
    "movie_genres": movie_genres,
    "movie_writers": movie_writers,
    "movie_keywords": movie_keywords,
    "movie_cast": movie_cast_clean,
    "movie_reviews": movie_reviews_clean
}

for name, table in supporting_tables.items():
    unmatched = (~table["movie_id"].isin(movie_ids)).sum()

    print(
        f"{name}: {len(table)} rows, "
        f"{unmatched} rows with unmatched movie IDs"
    )

Duplicate movie IDs: 0
movie_genres: 18159 rows, 0 rows with unmatched movie IDs
movie_writers: 4635 rows, 0 rows with unmatched movie IDs
movie_keywords: 85720 rows, 0 rows with unmatched movie IDs
movie_cast: 59674 rows, 0 rows with unmatched movie IDs
movie_reviews: 8900 rows, 13 rows with unmatched movie IDs

In [37]:
movie_reviews_clean = movie_reviews_clean[
    movie_reviews_clean["movie_id"].isin(movie_ids)
].copy().reset_index(drop=True)

print("Reviews remaining:", len(movie_reviews_clean))

Reviews remaining: 8887

In [38]:
(~movie_reviews_clean["movie_id"].isin(movie_ids)).sum()

np.int64(0)

In [39]:
print("Movies:", movies_table.shape)
print("\nMissing values in movies table:")
print(movies_table.isna().sum())

print("\nDuplicate movie IDs:", movies_table["movie_id"].duplicated().sum())

print("\nDuplicate genre records:",
      movie_genres.duplicated(subset=["movie_id", "genre"]).sum())

print("Duplicate writer records:",
      movie_writers.duplicated(subset=["movie_id", "writer"]).sum())

print("Duplicate keyword records:",
      movie_keywords.duplicated(subset=["movie_id", "keyword"]).sum())

print("Duplicate cast records:",
      movie_cast_clean.duplicated(subset=["movie_id", "actor", "character"]).sum())

print("Duplicate review IDs:",
      movie_reviews_clean["review_id"].duplicated().sum())

Movies: (6764, 15)

Missing values in movies table:
movie_id                0
title                   0
movie_url               0
poster_url              6
release_date            0
overview               21
user_score            125
director               15
status                  0
original_language       0
budget               1839
revenue              1592
content_score           0
release_year            0
runtime_minutes        63
dtype: int64

Duplicate movie IDs: 0

Duplicate genre records: 0
Duplicate writer records: 0
Duplicate keyword records: 0
Duplicate cast records: 0
Duplicate review IDs: 0

In [40]:
movies_table[
    ["user_score", "content_score", "release_year", "runtime_minutes", "budget", "revenue"]
].describe()

,user_score,content_score,release_year,runtime_minutes,budget,revenue
count,6639.00000,6764.000000,6764.000000,6701.000000,4.925000e+03,5.172000e+03
mean,6.68853,99.211709,2009.447221,107.291598,4.376721e+07,1.274439e+08
std,0.83656,4.637357,15.916954,23.917527,5.114411e+07,2.146333e+08
min,1.00000,35.000000,1902.000000,2.000000,1.000000e+00,6.000000e+00
25%,6.19250,100.000000,2002.000000,94.000000,1.050000e+07,1.587426e+07
50%,6.70000,100.000000,2014.000000,105.000000,2.500000e+07,5.372882e+07
75%,7.25600,100.000000,2022.000000,119.000000,5.800000e+07,1.460959e+08
max,10.00000,100.000000,2027.000000,261.000000,6.588000e+08,2.923706e+09

In [41]:
movies_table["status"].value_counts(dropna=False)

status
Released           6723
Post Production      33
In Production         7
Planned               1
Name: count, dtype: int64

In [42]:
movies_table["original_language"].value_counts().head(15)

original_language
English               5683
Japanese               214
French                 169
Spanish; Castilian     121
Korean                 109
Italian                 66
Chinese                 65
German                  50
Cantonese               44
Hindi                   26
Tagalog                 23
Portuguese              20
Russian                 16
Tamil                   14
Danish                  14
Name: count, dtype: int64

In [43]:
print("Lowest budgets:")

movies_table.nsmallest(10, "budget")[
    ["movie_id", "title", "release_year", "budget", "revenue"]
]

Lowest budgets:

      movie_id                      title  release_year  budget    revenue
5412    916405             The Quiet Girl          2022     1.0        6.0
3748       220               East of Eden          1955     2.0  5000000.0
127    1007757                    Swapped          2026     7.0        7.0
6164    413337            Girl in the Box          2016    20.0        NaN
4961   1768489              In The Middle          2026   100.0        NaN
5429    620498  Fabian: Going to the Dogs          2021   178.0        NaN
4236   1592947                        Sex          2026   200.0        NaN
6718   1355303            Pictureman News          2025   500.0        NaN
4504   1768217               Plan Hormiga          2026   700.0        NaN
3389    537971                        Mia          2017   800.0        NaN

In [44]:
print("Lowest revenues:")

movies_table.nsmallest(10, "revenue")[
    ["movie_id", "title", "release_year", "budget", "revenue"]
]

Lowest revenues:

      movie_id                  title  release_year      budget  revenue
5412    916405         The Quiet Girl          2022         1.0      6.0
127    1007757                Swapped          2026         7.0      7.0
2889   1064486      Memoir of a Snail          2024   4350000.0      7.0
1712    906126    Society of the Snow          2024  65500000.0   1281.0
6380     15849              The Mummy          1932    196000.0   1408.0
1406     11430       The Lion King 1½          2004         NaN   1465.0
5331     10234            Funny Games          1997         NaN   2506.0
4605       839                   Duel          1971    450000.0   2544.0
5664      6404  Nosferatu the Vampyre          1979   1400000.0   3451.0
3572     22164         Blood and Bone          2009   3700000.0   3492.0

In [45]:
low_budget = movies_table["budget"].notna() & (movies_table["budget"] < 1000)
low_revenue = movies_table["revenue"].notna() & (movies_table["revenue"] < 1000)

print("Suspiciously low budgets:", low_budget.sum())
print("Suspiciously low revenues:", low_revenue.sum())

movies_table.loc[
    low_budget | low_revenue,
    ["movie_id", "title", "release_year", "budget", "revenue"]
]

Suspiciously low budgets: 10
Suspiciously low revenues: 3

      movie_id                      title  release_year     budget    revenue
127    1007757                    Swapped          2026        7.0        7.0
2889   1064486          Memoir of a Snail          2024  4350000.0        7.0
3389    537971                        Mia          2017      800.0        NaN
3748       220               East of Eden          1955        2.0  5000000.0
4236   1592947                        Sex          2026      200.0        NaN
4504   1768217               Plan Hormiga          2026      700.0        NaN
4961   1768489              In The Middle          2026      100.0        NaN
5412    916405             The Quiet Girl          2022        1.0        6.0
5429    620498  Fabian: Going to the Dogs          2021      178.0        NaN
6164    413337            Girl in the Box          2016       20.0        NaN
6718   1355303            Pictureman News          2025      500.0        NaN

In [46]:
movies_table.loc[movies_table["budget"] < 1000, "budget"] = np.nan
movies_table.loc[movies_table["revenue"] < 1000, "revenue"] = np.nan

In [47]:
print("Budgets below $1,000:", (movies_table["budget"].dropna() < 1000).sum())
print("Revenues below $1,000:", (movies_table["revenue"].dropna() < 1000).sum())

print("Movies remaining:", len(movies_table))

Budgets below $1,000: 0
Revenues below $1,000: 0
Movies remaining: 6764

In [48]:
# Main movie table
movie_text_columns = [
    "title",
    "movie_url",
    "poster_url",
    "overview",
    "director",
    "status",
    "original_language"
]

for col in movie_text_columns:
    movies_table[col] = (
        movies_table[col]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )


# Genres, writers and keywords
for df, col in [
    (movie_genres, "genre"),
    (movie_writers, "writer"),
    (movie_keywords, "keyword")
]:
    df[col] = df[col].astype("string").str.strip().replace("", pd.NA)


# Cast
for col in ["actor", "character"]:
    movie_cast_clean[col] = (
        movie_cast_clean[col]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )


# Reviews
for col in ["author", "review_text"]:
    movie_reviews_clean[col] = (
        movie_reviews_clean[col]
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

In [49]:
movies_table.isna().sum()

movie_id                0
title                   0
movie_url               0
poster_url              6
release_date            0
overview               21
user_score            125
director               15
status                  0
original_language       0
budget               1849
revenue              1595
content_score           0
release_year            0
runtime_minutes        63
dtype: int64

In [50]:
# Genres
movie_genres = movie_genres.dropna(subset=["movie_id", "genre"])
movie_genres = movie_genres.drop_duplicates(
    subset=["movie_id", "genre"]
).reset_index(drop=True)

# Writers
movie_writers = movie_writers.dropna(subset=["movie_id", "writer"])
movie_writers = movie_writers.drop_duplicates(
    subset=["movie_id", "writer"]
).reset_index(drop=True)

# Keywords
movie_keywords = movie_keywords.dropna(subset=["movie_id", "keyword"])
movie_keywords = movie_keywords.drop_duplicates(
    subset=["movie_id", "keyword"]
).reset_index(drop=True)

# Cast
movie_cast_clean = movie_cast_clean.dropna(
    subset=["movie_id", "actor"]
)
movie_cast_clean = movie_cast_clean.drop_duplicates(
    subset=["movie_id", "actor", "character"]
).reset_index(drop=True)

# Reviews
movie_reviews_clean = movie_reviews_clean.dropna(
    subset=["movie_id", "review_id"]
)
movie_reviews_clean = movie_reviews_clean.drop_duplicates(
    subset=["review_id"]
).reset_index(drop=True)

In [51]:
print("Movies:", movies_table.shape)
print("Genres:", movie_genres.shape)
print("Writers:", movie_writers.shape)
print("Keywords:", movie_keywords.shape)
print("Cast:", movie_cast_clean.shape)
print("Reviews:", movie_reviews_clean.shape)

Movies: (6764, 15)
Genres: (18159, 2)
Writers: (4635, 2)
Keywords: (85720, 2)
Cast: (59674, 3)
Reviews: (8887, 5)

In [52]:
movies_table.to_csv("movies_table_clean.csv", index=False, date_format="%Y-%m-%d")

movie_genres.to_csv("movie_genres_clean.csv", index=False)
movie_writers.to_csv("movie_writers_clean.csv", index=False)
movie_keywords.to_csv("movie_keywords_clean.csv", index=False)

movie_cast_clean.to_csv("movie_cast_clean.csv", index=False)
movie_reviews_clean.to_csv("movie_reviews_clean.csv", index=False)

In [55]:
from sqlalchemy import create_engine, URL

connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="12345",
    host="localhost",
    port=3306,
    database="tmdb_movie_project"
)

engine = create_engine(connection_url)

In [56]:
from sqlalchemy import text

with engine.connect() as connection:
    print(connection.execute(text("SELECT DATABASE()")).scalar())

tmdb_movie_project

In [57]:
movies_table.to_sql(
    name="movies",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=500
)

6764

In [58]:
movie_genres.to_sql(
    name="movie_genres",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

18159

In [59]:
movie_writers.to_sql(
    name="movie_writers",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

4635

In [60]:
movie_keywords.to_sql(
    name="movie_keywords",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

85720

In [62]:
movie_cast_clean.to_sql(
    name="movie_cast",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

59674

In [63]:
movie_reviews_clean.to_sql(
    name="movie_reviews",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=500
)

8887